# Generated by Django 4.0.6 on 2022-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='War92',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.TextField()),
                ('name', models.TextField()),
                ('pit_hit', models.TextField()),
                ('position', models.TextField()),
                ('team', models.TextField()),
                ('war', models.TextField()),
            ],
        ),
    ]
